//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankSimulation.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class BankTransaction
    {
        public int BankTransactionID { get; set; }
        public int BankID { get; set; }
        public System.DateTime Date { get; set; }
        public string BankTransactionType { get; set; }
        public double BankTransactionAmount { get; set; }
        public string BankTransactionCurrency { get; set; }
    }
}
