//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankSimulation.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bank
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Bank()
        {
            this.Customers = new HashSet<Customer>();
        }
    
        public int BankID { get; set; }
        public string BankName { get; set; }
        public string BankPassword { get; set; }
        public string BankAccountMoneyAccountNumber { get; set; }
        public string BankAccountMoneyCurrency { get; set; }
        public double BankAccountMoneyBalance { get; set; }
        public string CentralBankMoneyAccountNumber { get; set; }
        public string CentralBankMoneyCurrency { get; set; }
        public double CentralBankMoneyBalance { get; set; }
        public int NumberOfCustomers { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Customer> Customers { get; set; }
    }
}
