//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankSimulation.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public int CustomerID { get; set; }
        public string CustomerName { get; set; }
        public string CustomerPassword { get; set; }
        public string CustomerAccountNumber { get; set; }
        public string CustomerAccountNumberCurrency { get; set; }
        public double CustomerAccountNumberBalance { get; set; }
        public string CustomerCreditAccount { get; set; }
        public string CustomerCreditAccountCurrency { get; set; }
        public double CustomerCreditAccountBalance { get; set; }
        public int BankID { get; set; }
    
        public virtual Bank Bank { get; set; }
    }
}
