//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankSimulation.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerTransaction
    {
        public int CustomerTransactionID { get; set; }
        public int CustomerID { get; set; }
        public System.DateTime Date { get; set; }
        public string CustomerTransactionType { get; set; }
        public double CustomerTransactionAmount { get; set; }
        public string CustomerTransactionCurrency { get; set; }
        public string BeneficiaryName { get; set; }
        public string BeneficiaryAccountNumber { get; set; }
        public int LoanFromBank { get; set; }
    }
}
